services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: calc-backend
    ports:
      - "6060:6060"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: calc-frontend
    ports:
      - "5959:5959"
    depends_on:
      - backend
